name: Publish to GitHub Pages

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Create release directory
        run: |
          VERSION=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')  # Получаем имя тега
          mkdir -p build/$VERSION  # Создаём директорию для версии

      - name: Move build files
        run: mv * build/$VERSION/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/$VERSION
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'
